title: Welcome to Simon Martin's homepage on github!
author: Simon Martin
email: s.j.martin<at>lboro.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Things I need to remember.
# social links
twitter_username: @drsimonmaritn
github_username:  mpsjm

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman

