title: Welcome to Simon Martin's homepage on github!
author: Simon Martin
email: s.j.martin<at>lboro.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Things I need to remember.
# social links
twitter_username: drsimonmartin
github_username:  mpsjm

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima

paginate: 5 # amount of posts to show
paginate_path: /page:num/

